### ISSUE TITLE
Getting TypeError on Arabic language. working fine in english language of website.

### ISSUE THREAD

**Issue by iamdharmesh** [iyzico/iyzipay-woocommerce#16]
Hello There, 

I am Using this plugin and getting Javascipt type error in arabic language of website while its working fine in english version of website. 
**Error:**
TypeError: iyziPay.localization.locales[iyziPay.memory.currentLocale] is undefined

![image](https://user-images.githubusercontent.com/10613171/46952038-52ad3900-d0a7-11e8-8fe8-53961c4c9635.png)

Any help? 

Let me know if you need more details on this.

Thanks,
Dharmesh Patel

**Comment by mehmetselim** [comment]
Hello ,

Our system is currently supporting Turkish and English. For other languages please use locale = 'en' 

Best,
