### ISSUE TITLE
Version differences between github.com and wordpress.org

### ISSUE THREAD

**Issue by halilemreozen** [iyzico/iyzipay-woocommerce#21]
Hello Guys, I have a few questions about this repo:
 
1) It seems "iyzico/iyzipay-woocommerce" repo master branch has 1.1.3 and develop branch has 1.1.0 versions of this plugin but "iyzico-woocommerce" plugin on wordpress.org has 1.1.4 version.
Do you guys continue to develop on another platform? Can you keep this repo updated as well?

2) Is there any specific reason to use two different names for repository and plugin.
 (iyzipay-woocommerce / iyzico-woocommerce)

PS:

I would be appreciated if you covered the migration cases for the previous users of KahveDigital IYZICO plugin.

**Comment by mehmetselim** [comment]
Hello @halilemreozen,  I am from the iyzico developer team

you can always access the stable current version at https://wordpress.org/plugins/iyzico-woocommerce/.

we will synchronize with github repo in the nearest time.
Thank you for feedback.
