### ISSUE TITLE
subMerchantKey Hatası

### ISSUE THREAD

**Issue by Engineercc** [iyzico/iyzipay-woocommerce#22]
Selamlar.Ödeme sistemini çalıştırdığımız zaman, kart bilgileri formunun gelmesi gereken yerde "Marketplace üye iş yeri için ürün ödemesinde bütün sepet kırılımlarında subMerchantKey gönderilmelidir" gibi bir uyarı geliyor. "subMerchantKey " girilmesi gerektiğini biliyorum fakat hangi php dosyasının içine eklendiğini çözemedim.  Iyzi-pay dokümantasyonunda her şey gayet açık anlatılmış fakat iyzico-woocommerce eklentisinde subMerchantKey ile ilgili bir şey bulamadım.

**Comment by enginozsozgun** [comment]
Merhaba @Engineercc , 
Mail adresinizi entegrasyon@iyzico.com a iletebilirseniz örnek kod ve gerekli dökümanları paylaşmaktan memnuniyet duyarız

**Comment by huseyinyildirim** [comment]
Bu hatayı bende aldım. Dökümanlarda bununla ilgili bir şey bulamadım. Nasıl çözüyoruz?

**Comment by mahmoud-193** [comment]
I also have the same error and I can't fix it please iyzico help
