### ISSUE TITLE
TLS 1.2 Problem

### ISSUE THREAD

**Issue by srht** [iyzico/iyzipay-woocommerce#25]
When I installed the plugin it gives this error: "your TLS version must be minimum 1.2. please upgrade your openssl version to minimum 1.01" and just display iyzico loading icon. 

I use lets encrypt ssl with TLS 1.2 version. Also I provided the TLS 1.2 protocol enabled on windows server. 

What could be the problem?

**Comment by sozgat** [comment]
Hello @srht , I am from the iyzico developer team.

We are sorry for the late response. If the problem continues, could you contact our integration team via email ( entegrasyon@iyzico.com )?

Sincerely yours,
Said
