### ISSUE TITLE
On-hold / Pending Woocommerce Durumlarına Karşılık Gelmiyor

### ISSUE THREAD

**Issue by SemihCag** [iyzico/iyzipay-woocommerce#27]
Merhaba, 
iyzico Ödeme Formu içerisindeki "Sipariş Durumu" woocommerce ile farklı kalıyor. 

Woocommerce Oh-hold  => Ödeme bekleniyor
Eklentide Oh-hold => Bekleniyor

Woocommerce pending => Beklemede
Eklentide pending => Ödeme bekleniyor. 

Sanırım sadece çeviri hatası.

**Comment by feyzullahdemir** [comment]
Merhaba ,
Size yardımcı olabilmesi için entegrasyon ekibimizle [entegrasyon@iyzico.com](mailto:entegrasyon@iyzico.com) iletişime geçebilir misiniz ?

Teşekkürler.
