### ISSUE TITLE
3.2.4 ile gelen yeni tablolar

### ISSUE THREAD

**Issue by ugurgok** [iyzico/iyzipay-woocommerce#33]
Selamlar,

3.2.6 sürümüne geçince iyzico_order bulunamadı şeklinde bir hata alınıyor. İnceleyince 3.2.4'de yeni tabloların eklendiğini farkettim fakat sadece plugin aktif edince çalışıyor. Benim gibi önceden iyzico kullananlar hata alacaktır. Plugini deaktif edip tekrar aktif edince tabloları ekleyebildiği için düzeliyor. 

İlgili hata:

`15306#0: *3725562 FastCGI sent in stderr: "PHP message: WordPress database error Table 'db.wp_iyzico_order' doesn't exist for query ALTER TABLE `wp_iyzico_order`
MODIFY COLUMN `payment_id` bigint(11) NOT NULL; made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Iyzico_For_WooCommerce->init, Iyzico_For_WooCommerce::paymentIdAlterTable, QM_DB->queryPHP message: You have attempted to register a duplicate item with WooCommerce Navigation: `checkout-form`" while reading response header from upstream	`

Emin değilim fakat plugin güncelleyince deaktif edip tekrar aktif etmesi gerekiyordu. Güncelleme bir şekilde deaktif/aktif işlemini yapmamış olabilir. 

Benim gibi hatayla karşılaşanlar bu şekilde çözebilir.

**Comment by feyzullahdemir** [comment]
Merhaba @ugurgok ,
Öncelikle yaşadığınız sorun için çok üzgün olduğumuzu belirtmek isterim.Sizinde bahsettiğiniz gibi aktif/deaktif fonksiyonları mevcut.Tabloda ki bir type değişikliği için Alter table eklemesi yapıldı.Plugin aktif edildiğinde ilgili table type update edilmesi gerekiyor.İlgili kod bloğu kontrol edebilirsiniz https://github.com/iyzico/iyzipay-woocommerce/blob/develop/woocommerce-gateway-iyzico.php#L98
Alter table işlemini yapılmasını engelleyen bir durum olmuş olabilir.Bunlara farklı eklentilerin çakışması sebep oluyor olabilir.

Teşekkürler,
Feyzullah Demir
