### ISSUE TITLE
Popup problemi

### ISSUE THREAD

**Issue by oguzn** [iyzico/iyzipay-woocommerce#34]
Ödeme sayfasında açılan iyzico popup ekranı çok dar, içerikler sığmıyor, kapatma butonu ekranda görünmüyor, overlay alanlara tıklayarak kapanmıyor,  kredi kartı ile ödeme yapma butonu neredeyse görünmüyor, bu konuda bir güncelleme iyi olur, ayrıca popup açılında kredi kartı alanları yerine iyzico üzerinden ödeme yapma ekranı geliyor ki bu bir çok müşteri için anlaşılmaz bir durum, bu site sahibinin tercihinde olmalı.

**Comment by feyzullahdemir** [comment]
Merhaba @oguzn ,
Öncelikle geri bildiriminiz için teşekkür ederiz.Böyle durumlarda ödeme ekranında sorun yaşanmaması için eklenti içerisine 2 adet ödeme formu görünümü ekledik.Eğer sorun yaşarsanız Responsive olarak ödeme formu görünümü seçebilirsiniz.

Teşekkürler,

**Comment by oguzn** [comment]
Merhaba, cevabınız için teşekkürler, ödeme ekranında Kredi Kartı ile Ödeme ekranın öncelikli geleceği bir seçenek eklense çok iyi olur, direkt İyzico ile Öde ekranı geliyor kullanıcının giriş yapması, üye olması vb. aşamaları olduğu içinde kullanışlı olmuyor. En azından bunu seçme şansımız olsa güzel olur.

**Comment by feyzullahdemir** [comment]
bu konu ile ilgili entegrasyon@iyzico.com adresine mail atıp ödeme ekranı görünümün değiştirilmesini istemeniz yeterli olacaktır.
