### ISSUE TITLE
Eklenti yok satıyor.

### ISSUE THREAD

**Issue by pasamsin** [iyzico/iyzipay-woocommerce#35]
Merhaba, eklenti yok satıyor ve fazladan stok düşüyor. Ürün yok satmaya açık değil. Bu sorunu her zaman yapmıyor. Kapıda ödeme ve eft ve havale yöntemlerinde herhangi bir sorun olmuyor. Database i kontrol ettim stoğun iki defa düşmesi normal değil aynı saat içerisinde aynı üründen başkası bir satın alım yapmamış.

![Ekran Resmi 2023-09-15 09 04 30](https://github.com/iyzico/iyzipay-woocommerce/assets/25478013/d007b579-4a34-4e17-879e-cacc60b29873)
![Ekran Resmi 2023-09-21 12 18 50](https://github.com/iyzico/iyzipay-woocommerce/assets/25478013/ae9feba7-1ea9-4397-876e-a1d2e02449ed)
![Ekran Resmi 2023-09-21 12 16 40](https://github.com/iyzico/iyzipay-woocommerce/assets/25478013/f6461b64-e34a-41ef-b683-6815320846a8)

**Comment by feyzullahdemir** [comment]
bug fixed
