### ISSUE TITLE
HPOS desteği mevcut mu?

### ISSUE THREAD

**Issue by gidhublan** [iyzico/iyzipay-woocommerce#36]
Merhaba, 

https://woo.com/document/high-performance-order-storage/

https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book 

yeni woocommerce sürümlerinde bu standart hale gelmiş.

**Comment by tarikkamat** [comment]
Selamlar, 3.5.7 sürümümüzde kullanabilirsiniz.

**Comment by tarikkamat** [comment]
Selamlar, 3.5.7 sürümümüzde kullanabilirsiniz.
