### ISSUE TITLE
Woocommerce Save Button Working 

### ISSUE THREAD

**Issue by ZgrK** [iyzico/iyzipay-woocommerce#8]
Hello all,

When I install o plugin then upgrade the plugin the last version after all woocommerce save button is not working you can see my issues from woocomerce https://github.com/woocommerce/woocommerce/issues/20595  need to test this

**Comment by ZgrK** [comment]
Version 1.0.3

**Comment by ZgrK** [comment]
On wordpress plugin system has version 1.0.3 in that version have this script 

`jQuery(document).ready(function(){jQuery("#mainform").submit(function(a){var e,i,r;if(e=jQuery("#woocommerce_iyzico_api_type").val(),i=jQuery("#woocommerce_iyzico_api_key").val(),r=jQuery("#woocommerce_iyzico_secret_key").val(),""!=i&&""!=r||alert("Api Key ve Secret Key Boş Bırakılamaz !"),"https://sandbox-api.iyzipay.com"==e){if("sandbox-"==i.substring(0,8)&&"sandbox-"==r.substring(0,8))return;alert("Sandbox / Test API için Live API Anahtarları kullanılamaz !")}else if("https://api.iyzipay.com"==e){if("sandbox-"!=i.substring(0,8)&&"sandbox-"!=r.substring(0,8))return;alert("Live API için Sandbox / Test API Anahtarları kullanılamaz !")}a.preventDefault()})});`

From this code making problem on saving all woocommerce setting **"#mainform"** woocommerce setting also use main system

**Comment by mehmetselim** [comment]
Hi @ZgrK , I am from the iyzico developer team. I started to work on fix for the new version of woocommerce. Thank you for your feedback.

**Comment by ZgrK** [comment]
@mehmetselim Thank you much for a reply that is fixed now on version 1.0.4
